### ISSUE TITLE
feat: Allow project-level config

### ISSUE THREAD

**Issue by delucis** [delucis/linter-dryer#4]
It would be useful if `linter-dryer`’s settings could be overridden on a per-project basis.

For example, a project could provide a `.dryer.yml` config file that could look like the following:

```yml
# .dryer.yml duplicating current defaults
minimumLines: 3
minimumTokens: 25
linterScope: file
ignoreFiles:
  - .gitignore
exclude:
  - "**/*.min.*"
severity: info
```
